//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isaac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjectTemplateQuestion
    {
        public int SubjectID { get; set; }
        public int TemplateID { get; set; }
        public Nullable<int> SubjectOrder { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
