//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isaac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template()
        {
            this.UserUseTemplates = new HashSet<UserUseTemplate>();
            this.subjectTemplateQuestions = new HashSet<subjectTemplateQuestion>();
            this.TemplateQuestions = new HashSet<TemplateQuestion>();
        }
    
        public int TemplateID { get; set; }
        public string Context { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModfiedDate { get; set; }
        public int UsedTime { get; set; }
        public int ModifiedTime { get; set; }
        public Nullable<int> AuthorName { get; set; }
        public int CategoryId { get; set; }
        public string TemplateSubject { get; set; }
        public string TemplateDescription { get; set; }
        public string TemplateTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUseTemplate> UserUseTemplates { get; set; }
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subjectTemplateQuestion> subjectTemplateQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateQuestion> TemplateQuestions { get; set; }
    }
}
