//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isaac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.PersonalTemplates = new HashSet<PersonalTemplate>();
            this.SubjectQuestion1 = new HashSet<SubjectQuestion1>();
            this.TemplateQuestions = new HashSet<TemplateQuestion1>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> Country { get; set; }
        public string Industry { get; set; }
        public string Company { get; set; }
        public string JobTitle { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> UserTitle { get; set; }
        public string emailAccount { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Gender Gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalTemplate> PersonalTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectQuestion1> SubjectQuestion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateQuestion1> TemplateQuestions { get; set; }
        public virtual UserTitle UserTitle1 { get; set; }
    }
}
