//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isaac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TemplateQuestion
    {
        public int TemplateID { get; set; }
        public string TemplateTitle { get; set; }
        public string Context { get; set; }
        public string TemplateDescription { get; set; }
        public string Questions { get; set; }
    }
}
